### PR TITLE
Updated instructions for TOR and SSL (Debian based distros)

### PR DESCRIPTION
**Pull request by PsySc0rpi0n**
I have upated the instructions for TOR and SSL configuration instructions. The existent ones were kind of outdated. I only updated for Linux (Debian based distros) and Android (for TOR).

Any improvements are welcome. I'm no expert and I might have made mistakes. This was my first contribution, if it can be called as such, to a "real" repository!

Hope it is useful!
Thanks
Psy

### CODE REVIEW

**Comment by bitbandi** [comment]
if you use nginx for ssl gateway only, it's better is you use ssl in nodejs directly:
https://stackoverflow.com/questions/5998694/how-to-create-an-https-server-in-node-js

**Comment by PsySc0rpi0n** [comment]
> if you use nginx for ssl gateway only, it's better is you use ssl in nodejs directly: https://stackoverflow.com/questions/5998694/how-to-create-an-https-server-in-node-js

I have this setup with nginx now. So, I'm not even going to think about changing. heheh. But thanks for suggesting. I just tried to update instructions for what was already here!

**Comment by bitbandi** [comment]
if you have already an nginx server with many vhost, than it's a good choice to use as reverse proxy. But if you run nginx for rtl only, it's "useless", yet another thing that can go wrong (murphy's law :D )

**Comment by mdconaway** [comment]
Hey @bitbandi
I just added PR #1026
This should add pretty much all of the possible SSL features.

**Pull request merged**
