### PR TITLE
fix: color coding in open channels table

### LINKED ISSUE #1154: Inconsistent color code for inactive channels
**Describe the bug**
Pending and Inactive channels have inconsistent color coding.

Inactive should be yellow, pending should be gray.

**To Reproduce**
1. have one inactive and one pending channel
2. pending channel color on the home page (operator layout) is different from channels page

**Screenshots**
Screenshot 2022-12-21 at 2 53 26 PM
Screenshot 2022-12-21 at 2 53 35 PM

**Your environment**
* Version of `RTL` 0.13.2
* Version of `lnd`/`core lightning`/`eclair` LND 
* Version of `btcd`, `bitcoind`, or other backend Neutrino
* Browser & browser version Chrome
* Operating system (`uname -a` on *Nix) MacOS
* any other relevant environment details

**Additional context**

### PR DESCRIPTION
**Pull request by abhiShandy**
fixes #1154

### CODE REVIEW

**Comment by ShahanaFarooqui** [comment]
@abhiShandy Good catch but I would prefer to keep dashboard colours same and change inactive colour in Open channels.

**Comment by abhiShandy** [comment]
alright

**Comment by ShahanaFarooqui** [comment]
You also need to build the `frontend` if anything is changed in `src` folder by running `npm run buildfrontend`. 

Likewise, if anything is updated within `server` folder, `backend` needs to be compiled by `npm run buildbackend`.

**Comment by abhiShandy** [comment]
I need your help in solving these conflicts.

**Comment by ShahanaFarooqui** [comment]
Resolved conflicts and merged the PR. Thank you for your contribution.

**Pull request merged**
